apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: infra
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: infra
    app.kubernetes.io/part-of: infra
  name: infra
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: infra
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: infra
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-acs-tenant/infra/infra@sha256:42d9cc6333607b59302cdd74fd2d88512027dafd05e8572b00784cba8cd37ba4
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8443
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
