apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: infra
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: infra
    app.kubernetes.io/part-of: infra
  name: infra
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: infra
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: infra
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-acs-tenant/infra/infra@sha256:5ee0d7a852626e3ac9425dbdd14dfa2817a4bd93feda9b2dfd982e0190fa43bb
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8443
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
