apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: infra
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: infra
    app.kubernetes.io/part-of: infra
  name: infra
spec:
  ports:
  - port: 8443
    targetPort: 8443
  selector:
    app.kubernetes.io/instance: infra
status:
  loadBalancer: {}
