apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: infra
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-acs-tenant/infra/infra@sha256:588c5401e1f64868a879fcc1f1da5adfc89805b278cb1fc2fa155aacb40c3d92
        name: container-image
        resources: {}
status: {}
