apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: infra
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-acs-tenant/infra/infra@sha256:a340adaec53a40f49c775dd1356c26f7d691838bdd2bee7cf8ec459310ca4f17
        name: container-image
        resources: {}
status: {}
