apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: infra
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: infra
    app.kubernetes.io/part-of: infra
  name: infrap6af
spec:
  port:
    targetPort: 8443
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: infra
    weight: 100
status: {}
