apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: infra
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-acs-tenant/infra/infra@sha256:2e02ca801bc9185c38e5688de6f72640bcc02e95098b58b87b4fb944fcc8f6a1
        name: container-image
        resources: {}
status: {}
