apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: infra
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-acs-tenant/infra/infra@sha256:0f80abab4ac10efe9813126ca507f33d76a6ad4ee23eef369eaf4498d6efbbd2
        name: container-image
        resources: {}
status: {}
