apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: infra
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rh-acs-tenant/infra/infra@sha256:47572e5d651562c49d97ef84e2f6ac49bd197b4911ca01206ca5aed1896ab070
        name: container-image
        resources: {}
status: {}
